import React from 'react';
import {Dimensions, StyleSheet} from 'react-native';
import {moderateScale} from '../../../Theme/Dimensions';
import Theme from '../../../Theme/Theme';
const {height, width} = Dimensions.get('window');
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  mainHeader: {
    height: (height / 100) * 10,
    // backgroundColor: 'red',
    flexDirection: 'row',
    alignItems: 'center',
    //   justifyContent: 'center',
  },
  buttonView: {
    height: 45,
    width: 45,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: moderateScale(18),
  },
  sliderButton: {
    height: 45,
    width: 45,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: moderateScale(145),
  },
  ButtonView: {
    height: (height / 100) * 10,
    width: (width / 100) * 90,
    backgroundColor: 'white',
    borderRadius: 18,
    marginLeft: moderateScale(20),
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 5,
  },
  expensesView: {
    height: (height / 100) * 8,
    width: (width / 100) * 50,
    // backgroundColor: 'white',
    borderRadius: 18,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  TotalView: {
    height: (height / 100) * 18,
    //   backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  additionView:{
    height: (height / 100) * 12,
    // backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  cricleMainView:{
    height: (height / 100) * 9,
    width: width,
    // backgroundColor: 'blue',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  circleView: {
    height: (height / 100) * 8,
    width: (height / 100) * 8,
    borderRadius: 45,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    marginLeft: moderateScale(10),
  },
  TextView:{
    height: (height / 100) * 3,
    width: width,
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  flatView2: {
    height: (height / 100) * 50,
    // backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  BurgerView2: {
    height: (height / 100) * 10,
    width: (width / 100) * 95,
    backgroundColor: 'white',
    borderRadius: 15,
    overflow: 'hidden',
    flexDirection: 'row',
    marginBottom: moderateScale(6),
    elevation: 5,
    alignItems: 'center',
    // justifyContent: 'center',
  },
  HomeView: {
    height: (height / 100) * 8,
    width: (height / 100) * 8,
    borderRadius: 45,
    backgroundColor: '#FFC507',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    marginLeft: moderateScale(10),
  },
  FoodView: {
    height: (height / 100) * 8,
    width: (height / 100) * 8,
    borderRadius: 45,
    backgroundColor: '#EE4814',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    marginLeft: moderateScale(10),
  },
  rechargeView: {
    height: (height / 100) * 8,
    width: (height / 100) * 8,
    borderRadius: 45,
    backgroundColor: '#23B567',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    marginLeft: moderateScale(10),
  },

  AddText:{
    fontSize: Theme.fontSizes.xmedium,
    color: 'black',
    marginLeft: moderateScale(21),
},
ClearText:{
    fontSize: Theme.fontSizes.xmedium,
    color: 'black',
    marginLeft: moderateScale(35),
},
shareText:{
    fontSize: Theme.fontSizes.xmedium,
    color: 'black',
    marginLeft: moderateScale(29),
},
  totalText: {
    fontSize: Theme.fontSizes.big,
    color: 'black',
  },
  dollarText: {
    color: 'black',
    fontSize: Theme.fontSizes.xxbig,
  },
  expensesText: {
    color: 'white',
    fontSize: Theme.fontSizes.xmedium,
  },
  incomeText: {
    fontSize: Theme.fontSizes.xxmedium,
    color: '#707A98',
    marginLeft: moderateScale(45),
  },
  textView: {
    fontSize: Theme.fontSizes.big,
    color: 'black',
    marginLeft: moderateScale(15),
  },
});
export default styles;
